import { SanityLive } from '@/sanity/lib/live';
import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Roboto } from 'next/font/google';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={`${roboto.className} antialiased`}>
          <Navbar />
          {children}
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
